import asyncio
from metaapi_cloud_sdk import MetaApi

# Token MetaApi
TOKEN = "EyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlNzRjNTE2NjhkNjRhZTJkODI2NGE3YTMzZWYxMzE0YyIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOmRlMWMyNjJiLTE3ZDQtNDE1Yy1iYjFmLWM0OWRiMDM0MmQyNSJdfSx7ImlkIjoibWV0YWFwaS1yZXN0LWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6ZGUxYzI2MmItMTdkNC00MTVjLWJiMWYtYzQ5ZGIwMzQyZDI1Il19LHsiaWQiOiJtZXRhYXBpLXJwYy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDpkZTFjMjYyYi0xN2Q0LTQxNWMtYmIxZi1jNDlkYjAzNDJkMjUiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDpkZTFjMjYyYi0xN2Q0LTQxNWMtYmIxZi1jNDlkYjAzNDJkMjUiXX0seyJpZCI6Im1ldGFzdGF0cy1hcGkiLCJtZXRob2RzIjpbIm1ldGFzdGF0cy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6ZGUxYzI2MmItMTdkNC00MTVjLWJiMWYtYzQ5ZGIwMzQyZDI1Il19LHsiaWQiOiJyaXNrLW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJyaXNrLW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOmRlMWMyNjJiLTE3ZDQtNDE1Yy1iYjFmLWM0OWRiMDM0MmQyNSJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiZTc0YzUxNjY4ZDY0YWUyZDgyNjRhN2EzM2VmMTMxNGMiLCJpYXQiOjE3OTExMjI0OTIsImV4cCI6MTc5ODg5ODQ5Mn0.gW6UZ-jCI-P1BcsU1RbAAFWXq5vhO7X8EoBvUAL5YhPaXC3x5eoFaRkekMYosCFqaG2CUBDF2N2RzwrPziFgE9uZDtQmBGGmPeYBKepQg-TvqVd7Jo3bNkygc4qseVWUr6zGH9IGxJYKWlyD9t4DwCPY07qCcMhzDLnXD4YRtrX97L0WYAy2Nr76q7QiZ3JWlz4Sz-0dRv5bJfnYAamiagC6YDVKXaGAyMFADgcL8vM-mnNcqGt1Fj2DlqRb-MTUf0KrX_CEKTTwVh64HT1EV_WYz80Kq4u72RMSWRjVBKmpmdjn69tvD204-Gxed8UOsEdSH_FBQ_3keVs4KXISSekgHYx0khLZSdjolQcsbKVoT6u-UWIALA83P_odEnJIt4uSWAAeWPjKDVEI1aXLVcymKq0CefMIlD-NYNlE0qLwruAI93zaPbOPsk23GCS7bGg-F_MsG58puU_NFgJs4VRBJXG7N07gZOuAtr5sgtda0nPOvzY3GFY353aeQwW9Xp4bMz1nzYSBOaf3H2wNuiCk0AQtrtIN3EHbAIK0YCuXt7GxGLLxOMKUeOBMYn1ZjcIfefwSj-_nTLmha_dOZVv8h_8rc2un7MwtNvLpCGm87n_efidtzPk5n39BmvqtLRTsCpNBXjawaDv7PAtcVAFxamqb2TYic4IL3duqsWg"

# ID de votre compte démo JustMarkets extrait de votre token
ACCOUNT_ID = "de1c262b-17d4-415c-bb1f-c49db0342d25"

async def test_connection():
    api = MetaApi(TOKEN)
    account = await api.metatrader_account_api.get_account(ACCOUNT_ID)
    
    print(f"Connexion au compte : {account.name}")
    print(f"Serveur : {account.server}")
    print(f"Statut : {account.state}")

    # Attendre que le compte soit connecté
    if account.state != 'DEPLOYED':
        print("Déploiement du compte...")
        await account.deploy()
        
    connection = account.get_rpc_connection()
    await connection.connect()
    await connection.wait_synchronized()

    # Récupérer les informations du compte
    account_information = await connection.get_account_information()
    print("Informations du compte :", account_information)

asyncio.run(test_connection())
